keys:
  - &primary age12u9y6zt83uztxczeykcte4ta60yagye6d89tgrr52jeq5csnpy8qadnlz9
  - &primaryssh age1ueeuvc0mp4g8q78dastadre87cmkvmw559xufsg4kl8xvtw4lvvsrcyqy4
creation_rules:
  - path_regex: src/secrets/secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *primaryssh
